USE splitmates_db;
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Wipe Counters', 'high', '2025-7-23', '2025-5-4');
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Mop Kitchen', 'medium', '2026-3-31', '2025-10-7');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Bathroom', 'high', '2026-1-11', '2026-3-30');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Clean Toilet', 'low', '2025-7-28', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Sweep Hallway', 'high', '2025-4-16', '2025-10-24');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Vacuum Living Room', 'high', '2025-8-27', '2025-5-22');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Take Out Trash', 'medium', '2025-9-3', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Toilet', 'high', '2025-6-27', '2025-6-19');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Do Laundry', 'medium', '2025-7-4', '2025-12-3');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Take Out Trash', 'high', '2025-11-5', '2025-10-8');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Bathroom', 'low', '2026-1-11', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Wash Dishes', 'high', '2025-9-24', '2026-4-11');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Fridge', 'high', '2025-11-9', '2025-4-23');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Sweep Hallway', 'medium', '2025-6-6', '2025-5-3');
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Wash Dishes', 'medium', '2026-1-14', '2025-7-10');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Bathroom', 'medium', '2025-8-17', '2026-1-1');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Fridge', 'high', '2026-4-4', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Sweep Hallway', 'high', '2025-10-27', '2025-12-25');
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Vacuum Living Room', 'medium', '2025-5-7', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Vacuum Living Room', 'medium', '2025-5-2', '2025-5-18');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Clean Bathroom', 'low', '2025-11-20', '2025-11-10');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Wipe Counters', 'low', '2025-10-3', '2025-7-4');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Bathroom', 'high', '2025-9-28', '2026-2-7');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Sweep Hallway', 'medium', '2025-9-10', '2025-5-27');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Take Out Trash', 'high', '2025-9-21', '2026-3-29');
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Take Out Trash', 'medium', '2025-6-7', '2026-3-20');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Vacuum Living Room', 'medium', '2026-1-23', '2026-1-7');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Wipe Counters', 'low', '2025-7-13', '2025-10-28');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Clean Fridge', 'medium', '2025-10-26', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Take Out Trash', 'low', '2026-2-18', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Vacuum Living Room', 'medium', '2025-6-7', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Clean Fridge', 'medium', '2025-12-3', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Do Laundry', 'medium', '2025-11-25', '2026-1-4');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Wipe Counters', 'medium', '2025-8-29', '2026-2-8');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Toilet', 'high', '2025-9-21', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Vacuum Living Room', 'high', '2025-6-30', '2025-10-6');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Clean Bathroom', 'low', '2026-4-11', '2025-11-28');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Mop Kitchen', 'medium', '2025-8-24', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Clean Toilet', 'high', '2026-1-4', '2025-6-26');
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Wash Dishes', 'high', '2026-3-12', '2025-7-12');
