USE splitmates_db;
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Wipe Counters', 'high', '7/23/2025', '5/4/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Mop Kitchen', 'medium', '3/31/2026', '10/7/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Bathroom', 'high', '1/11/2026', '3/30/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Clean Toilet', 'low', '7/28/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Sweep Hallway', 'high', '4/16/2025', '10/24/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Vacuum Living Room', 'high', '8/27/2025', '5/22/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Take Out Trash', 'medium', '9/3/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Toilet', 'high', '6/27/2025', '6/19/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Do Laundry', 'medium', '7/4/2025', '12/3/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Take Out Trash', 'high', '11/5/2025', '10/8/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Bathroom', 'low', '1/11/2026', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Wash Dishes', 'high', '9/24/2025', '4/11/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Fridge', 'high', '11/9/2025', '4/23/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Sweep Hallway', 'medium', '6/6/2025', '5/3/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Wash Dishes', 'medium', '1/14/2026', '7/10/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Bathroom', 'medium', '8/17/2025', '1/1/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Fridge', 'high', '4/4/2026', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Sweep Hallway', 'high', '10/27/2025', '12/25/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Vacuum Living Room', 'medium', '5/7/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Vacuum Living Room', 'medium', '5/2/2025', '5/18/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Clean Bathroom', 'low', '11/20/2025', '11/10/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Wipe Counters', 'low', '10/3/2025', '7/4/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (4, 'Clean Bathroom', 'high', '9/28/2025', '2/7/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Sweep Hallway', 'medium', '9/10/2025', '5/27/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Take Out Trash', 'high', '9/21/2025', '3/29/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Take Out Trash', 'medium', '6/7/2025', '3/20/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Vacuum Living Room', 'medium', '1/23/2026', '1/7/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Wipe Counters', 'low', '7/13/2025', '10/28/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Clean Fridge', 'medium', '10/26/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Take Out Trash', 'low', '2/18/2026', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Vacuum Living Room', 'medium', '6/7/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Clean Fridge', 'medium', '12/3/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Do Laundry', 'medium', '11/25/2025', '1/4/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Wipe Counters', 'medium', '8/29/2025', '2/8/2026');
insert into chores (group_id, title, effort, due_at, completed_at) values (1, 'Clean Toilet', 'high', '9/21/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Vacuum Living Room', 'high', '6/30/2025', '10/6/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (6, 'Clean Bathroom', 'low', '4/11/2026', '11/28/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (3, 'Mop Kitchen', 'medium', '8/24/2025', null);
insert into chores (group_id, title, effort, due_at, completed_at) values (5, 'Clean Toilet', 'high', '1/4/2026', '6/26/2025');
insert into chores (group_id, title, effort, due_at, completed_at) values (2, 'Wash Dishes', 'high', '3/12/2026', '7/12/2025');
